services:
  mysql_qriz:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=qriz
      - MYSQL_USER=qriz
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - qriz-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis_qriz:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - qriz-network

networks:
  qriz-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: